name: JS and CSS Linting

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use (defaults to 20)'
        required: false
        type: string
        default: '20'

permissions:
  contents: read
jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          # Installs project dependencies using npm in all defined workspaces, if present.
          # Uses a clean install to ensure a reproducible build environment.
          npm ci --workspaces --if-present

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint JS
        run: npm run lint:js
