name: JavaScript Testing

on:
  workflow_call:

jobs:
  test-js:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          # Install dependencies in subdirectories
          for dir in $(find . -type f -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;); do
            if [ "$dir" != "." ]; then
              echo "Installing dependencies in $dir"
              cd $dir
              npm ci
              cd -
            fi
          done

      - name: Run tests
        run: npm run test