name: Linting
on:
  workflow_call:
  workflow_dispatch:

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then
            composer install
          fi
          if [ -f package.json ]; then
            npm install
            npm install @wordpress/scripts --save-dev
          fi
          # Install dependencies in subdirectories
          for dir in $(find . -type f -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;); do
            if [ "$dir" != "." ]; then
              echo "Installing dependencies in $dir"
              cd $dir
              npm install
              cd -
            fi
          done

      - name: Validate Composer configuration
        run: |
          if [ -f composer.json ]; then
            OUTPUT=$(composer validate --no-check-publish)
            if grep -q 'ERROR' <<< "$OUTPUT"; then
              echo "Composer validation failed. Check the output for details."
              exit 1
            fi
          else
            echo "No composer.json found, skipping Composer validation."
          fi

      - name: Lint PHP
        run: |
          if [ -f composer.json ]; then
            OUTPUT=$(composer phpcs-allow-todo --no-check-publish 2>&1)
            echo "$OUTPUT" | tee phpcs_output.log
            if echo "$OUTPUT" | grep -q 'ERROR'; then
              echo "PHPCS found errors. Check phpcs_output.log for details."
              exit 1
            elif echo "$OUTPUT" | grep -q 'WARNING'; then
              echo "PHPCS found warnings. Check phpcs_output.log for details."
              # Optionally exit with a warning status
              exit 0
            else
              echo "PHPCS completed successfully, no errors or warnings."
            fi
          else
            echo "No composer.json found, skipping PHP linting."
          fi

      - name: Lint CSS
        run: |
          if [ -f package.json ]; then
            npm run lint:css
          else
            echo "No package.json found, skipping CSS linting."
          fi

      - name: Lint JS
        run: |
          if [ -f package.json ]; then
            npm run lint:js
          else
            echo "No package.json found, skipping JS linting."
          fi

      - name: Scan WordPress Patterns
        run: |
          if [ -d patterns ]; then
            if [ -f composer.json ]; then
              composer scan-wp-patterns
            else
              echo "No composer.json found, skipping WordPress patterns scan."
            fi
          else
            echo "No 'patterns' directory found, skipping WordPress patterns scan."
          fi
