name: WordPress Pattern Validation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pattern-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: |
          if [ ! -f composer.json ]; then
            echo "❌ No composer.json found - this workflow requires a PHP project with Composer"
            exit 1
          fi

          echo "📦 Installing Composer dependencies..."
          composer install

      - name: Validate Composer configuration
        run: |
          echo "🔍 Validating Composer configuration..."
          OUTPUT=$(composer validate --no-check-publish)

          if grep -q 'ERROR' <<< "$OUTPUT"; then
            echo "❌ Composer validation failed. Check the output above for details."
            exit 1
          fi

          echo "✅ Composer configuration is valid"

      - name: Check for patterns directory
        run: |
          echo "📁 Checking for WordPress patterns directory..."

          if [ ! -d patterns ]; then
            echo "⚠️  No 'patterns' directory found, skipping WordPress pattern validation."
            echo "This workflow is designed for projects with WordPress block patterns."
            exit 0
          fi

          echo "✅ Found patterns directory"

      - name: Validate WordPress patterns
        run: |
          echo "🔍 Running WordPress pattern validation..."

          # Check if scan-wp-patterns script exists in composer.json
          if ! grep -q '"scan-wp-patterns"' composer.json; then
            echo "⚠️  No scan-wp-patterns script found in composer.json, skipping pattern validation."
            echo "Please add a 'scan-wp-patterns' script to your composer.json file."
            exit 0
          fi

          # Run pattern validation and capture output
          echo "Running: composer scan-wp-patterns"
          OUTPUT=$(composer scan-wp-patterns --no-check-publish 2>&1)
          echo "$OUTPUT" | tee pattern_validation.log

          if echo "$OUTPUT" | grep -q 'ERROR'; then
            echo "❌ WordPress pattern validation found errors. Check pattern_validation.log for details."
            exit 1
          elif echo "$OUTPUT" | grep -q 'WARNING'; then
            echo "⚠️  WordPress pattern validation found warnings. Check pattern_validation.log for details."
            echo "    Warnings don't fail the build, but should be addressed."
            exit 0
          else
            echo "✅ WordPress pattern validation completed successfully - no errors or warnings found!"
          fi

    env:
      PATTERN_VALIDATION_LOG_FILE: pattern_validation.log
