name: WordPress PHP Testing

on:
  workflow_call:

jobs:
  test-php:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    env:
      # WordPress testing environment paths
      WP_CORE_DIR: /tmp/WordPress
      WP_TESTS_DIR: /tmp/WordPress/wordpress-tests-lib

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "rootpassword"
        ports:
          - 3306:3306
        # Ensures MySQL is healthy before running tests
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Install composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      # Installs the Subversion (SVN) package, which is required for setting up the WordPress test suite.
      # This step updates the package list and installs SVN using apt-get.
      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Setup WordPress test environment
        run: composer test-setup

      # Runs PHPUnit tests using the specified configuration file and outputs results in TestDox format.
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration vendor/bcgov/wordpress-utils/phpunit.xml.dist --testdox